/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: e218f6c6031da151dd7c51949bafe403)
interface __BaseEnv_Env {
	ROUTES: KVNamespace;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
